version: '3'
services:
  mongodb:
    image: mongo:6.0
    ports:
    - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=p4ssw0rd
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
    - 8081:8081
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=p4ssw0rd
    - ME_CONFIG_MONGODB_SERVER=mongodb