version: '3'
services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=4dm1np4ssw0rd
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=4dm1np4ssw0rd
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
  usermanager-api:
    image: usermanager-api
    depends_on:
      - mongodb
    ports:
      - 8089:8081
    environment:
      - MongoDB__ConnectionString=mongodb://admin:4dm1np4ssw0rd@mongodb:27017
      - MongoDB__Database=usermanager-db
      - JwtBearer__Authority=https://jwtgenerator.nrglabz.com/
      - JwtBearer__Audience=https://usermanager-api.nrglabz.com
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p4ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ~/.aspnet/https:/https:ro
