@UserManager_HostAddress = https://localhost:7298/api/v1
@JWT_Bearer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImdhYm9yIiwic3ViIjoiZ2Fib3IiLCJqdGkiOiJmZmZlZWNjMCIsImF1ZCI6InVzZXJtYW5hZ2VyLWFwaSIsIm5iZiI6MTcwMzY4NDQxMiwiZXhwIjoxNzExNTQ2ODEyLCJpYXQiOjE3MDM2ODQ0MTIsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.-CMSMBXIWhQpudCsWUeqz3bcbid29XsLHyzqu5MqhIw

### Get all users
GET {{UserManager_HostAddress}}/users
Authorization: Bearer {{JWT_Bearer}}
Accept: application/json

### Get one specific user
GET {{UserManager_HostAddress}}/users/13
Authorization: Bearer {{JWT_Bearer}}
Accept: application/json

### Get one specific user - non existing
GET {{UserManager_HostAddress}}/users/14121212
Authorization: Bearer {{JWT_Bearer}}
Accept: application/json

### Create user
POST {{UserManager_HostAddress}}/users
Content-Type: application/json
Authorization: Bearer {{JWT_Bearer}}

{
  "name": "Test User",
  "username": "testuser"
}

### Update user
PUT {{UserManager_HostAddress}}/users/13
Content-Type: application/json
Authorization: Bearer {{JWT_Bearer}}

{
  "name": "Test User",
  "username": "testuser"
}

### Patch user (change e-mail, website)
PATCH {{UserManager_HostAddress}}/users/13
Content-Type: application/json
Authorization: Bearer {{JWT_Bearer}}

{
  "update":
  [
    {
        "op": "replace",
        "path": "/email",
        "value": "me@company.net"
    },
    {
        "op": "replace",
        "path": "/website",
        "value": "https://www.company.net"
    }
  ]
}


### Patch user (remove address and company)
PATCH {{UserManager_HostAddress}}/users/13
Content-Type: application/json
Authorization: Bearer {{JWT_Bearer}}

{
  "update":
  [
    {
        "op": "remove",
        "path": "/address"
    },
    {
        "op": "remove",
        "path": "/company"
    }
  ]
}
